#ifndef MAIN_H
#define	MAIN_H

#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_GAUCHE_PROCHE 6
#define STATE_TOURNE_GAUCHE_PROCHE_EN_COURS 7
#define STATE_TOURNE_DROITE 8
#define STATE_TOURNE_DROITE_EN_COURS 9
#define STATE_TOURNE_DROITE_PROCHE 10
#define STATE_TOURNE_DROITE_PROCHE_EN_COURS 11
#define STATE_TOURNE_SUR_PLACE_GAUCHE 12
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 13
#define STATE_TOURNE_SUR_PLACE_DROITE 14
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 15
#define STATE_ARRET 16
#define STATE_ARRET_EN_COURS 17
#define STATE_RECULE 18
#define STATE_RECULE_EN_COURS 19
#define STATE_TETE_TETE 20
#define STATE_TETE_TETE_EN_COURS 21
#define STATE_TOURNE_EX_GAUCHE 22
#define STATE_TOURNE_EX_GAUCHE_EN_COURS 23
#define STATE_TOURNE_EX_DROITE 24
#define STATE_TOURNE_EX_DROITE_EN_COURS 25
#define STATE_FREINAGE1 26
#define STATE_FREINAGE1_EN_COURS 27
#define STATE_FREINAGE2 28
#define STATE_FREINAGE2_EN_COURS 29
#define STATE_COULOIR_TOURNE_GAUCHE 30
#define STATE_COULOIR_TOURNE_GAUCHE_EN_COURS 31
#define STATE_COULOIR_TOURNE_DROITE 32
#define STATE_COULOIR_TOURNE_DROITE_EN_COURS 33



#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_GAUCHE_PROCHE 2
#define OBSTACLE_EX_GAUCHE 3
#define OBSTACLE_A_DROITE 4
#define OBSTACLE_A_DROITE_PROCHE 5
#define OBSTACLE_EX_DROITE 6
#define OBSTACLE_EN_FACE_PROCHE 7
#define OBSTACLE_EN_FACE 8
#define OBSTACLE_EN_FACE_LOIN 9
#define OBSTACLE_EN_FACE_BIENTOT 10
#define COULOIR_OBS_DROITE 11
#define COULOIR_OBS_GAUCHE 12
#define OBSTACLE_A_DROITE_LOIN 13
#define OBSTACLE_A_GAUCHE_LOIN 14

//Config paramètres chip
#define FCY 40000000


void OperatingSystemLoop();

void SetNextRobotStateInAutomaticMode();

#endif	/* MAIN_H */

